apiVersion: v1
kind: Secret
metadata:
  name: gangway-data-values
  namespace: tanzu-system-auth
type: Opaque
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    infrastructure_provider: "aws"      
    gangway:
      image:
        repository: projects-stg.registry.vmware.com/tkg
      config:
        clusterName: {{ .Values.clusterName }}
        DEX_SVC_LB_HOSTNAME: {{ .Values.dexFQDN }}
        clientID: {{ .Values.clusterName }}
        APISERVER_URL: {{ .Values.apiServer }}
        scopes: ["openid","profile","email","offline_access","groups"]
      secret:
        sessionKey: {{ .Values.sessionKey }}
        clientSecret: {{ .Values.clientSecret }}
      service:
        type: NodePort
    dns:
      aws:
        GANGWAY_SVC_LB_HOSTNAME: {{ .Values.gangwayFQDN }}

    dex:
      ca: |
        {{ .Values.dexCA }}