apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gangway-ingress
  namespace: tanzu-system-auth
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.gangwayFQDN }}."
spec:
  tls:
  - secretName: gangway-https-secret
    hosts:
      - {{ .Values.gangwayFQDN }}
  rules:
  - host: {{ .Values.gangwayFQDN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: gangwaysvc
          servicePort: 443
