apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gangway-https-ingress
  namespace: tanzu-system-auth
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
spec:
  virtualhost:
    fqdn: {{ .Values.gangwayFQDN }}
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: gangwaysvc
      port: 443
  routes:
  - match: /
    services:
    - name: kuard
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-ingress
  namespace: tanzu-system-auth
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    external-dns.alpha.kubernetes.io/hostname: "example.com"
spec:
  tls:
  - secretName: gangway-https-secret
    hosts:
      - {{ .Values.gangwayFQDN }}
  rules:
  - host: example.com
    http:
      paths:
      - path: /dummy
        backend:
          serviceName: dummy
          servicePort: 80
