apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-extensions-harbor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.server }}
  project: default
  syncPolicy:
    automated: {}
  source:
    path: cd/argo/apps/extensions-ingress
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: domain
          value: "{{ .Values.harbor.domain }}"
        - name: commonPwd
          value: "{{ .Values.harbor.pwd }}"