clusterName: wlc
mgmtClusterName: mgmt
workersPerPool: "1"
dexFQDN: example.com
argoFQDN: example.com
argoPwd: topsecret
dexCA: |
  -----BEGIN CERTIFICATE-----
  ...cert...
  -----END CERTIFICATE-----