repoURL: https://gitlab.com/azwickey/tkg-autopilot.git
targetRevision: HEAD
server: https://kubernetes.api.lb:6443  # This must be overridden
mgmtClusterName: aws-mgmt
ingress:
  ingressFQDN: '*.mgmt.tanzu.zwickey.net'
  email: azwickey@gmail.com
argo:
  ingress: argo.mgmt.tanzu.zwickey.net
  pwd: "topsecret" # This must be overridden
dex:
  ingressFQDN: dex.mgmt.tanzu.zwickey.net
  clientId: 0oaagkq37j5IEbOqe4x6
  clientSecret: topSecret # This must be overridden
  idpUrl: https://dev-104945.okta.com/oauth2/default
  wlName1:  aws-workload1
  gangway1: gangway.workload1.tanzu.zwickey.net
  wlClientSecret1:  topsecret # This must be overridden
workload1:
  clusterName: aws-workload1
  workersPerPool: "2"
  