apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cluster-issuer
  namespace: default
spec:
  acme:
    email: "azwickey@gmail.com"
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: xxxx
          accessKeyID: xxxx
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
