#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: "aws"
contour:
  image:
    repository: projects-stg.registry.vmware.com/tkg
envoy:
  service:
    type: LoadBalancer
  image:
    repository: projects-stg.registry.vmware.com/tkg
