clusterName: wlc
dexFQDN: dex.example.com
apiServer: https://apiserver.com
sessionKey: 123123123asdasdasd
clientSecret: topsecret
gangwayFQDN: gangway.example.com
dexCA: |
    -----BEGIN CERTIFICATE-----
    MIIDNDCCAhygAwIBAgIRAK+5weYAN+liaEoUXUTZCqQwDQYJKoZIhvcNAQELBQAw
    IzEPMA0GA1UEChMGdm13YXJlMRAwDgYDVQQDEwd0a2ctZGV4MB4XDTIwMTAwOTEy
    MjAwMFoXDTIxMDEwNzEyMjAwMFowIzEPMA0GA1UEChMGdm13YXJlMRAwDgYDVQQD
    Ewd0a2ctZGV4MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoUA16jwZ
    R7AWfdmUSIzykg2LFEsPMKaav/piEtC/HRw6UXBZ27XmA3y4g4cvV44O8k8fQNrz
    igLoUJbVNtf94zQfL0BzcG8jYlQNxSBiJWa3ndazK8JcyvE/AlwqxLdPAIsTbpyU
    tQSSFRbHqtSjqxLX2Zm2IHbtx/vlR6DPkUxy2Wm3w8xO/UWz2p1JHS6wR8dbtmGg
    DmekdZNpjlKW62JVFxesWg8n/LGBv6FMQKggWvnQa8rYQsb/J23esLwUpftBgppf
    c11NXtCshVPdBzw6t2ktnjTGF0mNQSjmb961lrs1Tz5ko1oGYuUC5z34KNv60yk4
    VPgoS8iEbDurwwIDAQABo2MwYTAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDAYDVR0TAQH/BAIwADAyBgNVHREEKzApggt0a2ctZGV4LmNvbYIaZGV4Lm1n
    bXQudGFuenUuendpY2tleS5uZXQwDQYJKoZIhvcNAQELBQADggEBAHv5ScP6mQyA
    cDNg6bPthmjEd2PM7QV8FnxQb4xCzII9BUSwzD9yuj1nfaCAXfkO0MGS92TwAL7q
    hJtr1ogAArD0ltXICLJFoY47Z6JQ8pGZJKg9/IquYka6RItNuGNoKcTyvHmb6/1r
    nJ1BwIrPS8W9mFAzEYK4AZyvtzvTllD70VK3WnZKAw5yia29YmDbJsL2ifXYOKMa
    kjWAefKChzPJkSjOFplHS8BR0UcKwW9P/Vc9qjF5Z+vK7a4g3ddHDQStzsEFQWQH
    SOPmCVruTyB/RSwLGhcvUPjnA6gTDmXMXSXHnMZ7iMO+1Wa9wRhFHxSIEyc6Py2s
    +tiSupswxWs=
    -----END CERTIFICATE-----