kind: Service
apiVersion: v1
metadata:
  name: dex
  namespace: tanzu-system-auth
  labels:
    app: dex
spec:
  type: NodePort
  ports:
    - name: "dex"
      protocol: TCP
      port: 5555
      targetPort: "http"
  selector:
    app: dex